# Generated by Django 5.1.3 on 2024-11-13 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 22, 7, 36, 697747, tzinfo=datetime.timezone.utc)),
        ),
    ]
