# Generated by Django 5.1.3 on 2024-11-21 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_memberinvite_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 21, 57, 6, 736992, tzinfo=datetime.timezone.utc)),
        ),
    ]
